In [1]:
import numpy as np

In [2]:
y = np.array([10, 50, 100, 200, 70])

In [3]:
X = np.array([
    [30,  7, 1, 1.50],
    [40, 10, 0, 1.60],
    [50, 20, 1, 1.70],
    [60, 12, 0, 1.80],
    [25, 10, 1, 1.65]
])

In [4]:
X

array([[30.  ,  7.  ,  1.  ,  1.5 ],
       [40.  , 10.  ,  0.  ,  1.6 ],
       [50.  , 20.  ,  1.  ,  1.7 ],
       [60.  , 12.  ,  0.  ,  1.8 ],
       [25.  , 10.  ,  1.  ,  1.65]])

In [5]:
#betas = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
#betas

array([  3.6245864 ,  -0.16192052, -16.79784575, -29.73133514])

In [6]:
def fit(X, y):
    X = np.c_[np.ones(X.shape[0]), X]
    betas = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)

    intercept = betas[0]
    coef = betas[1:]

    return intercept, coef

In [7]:
X.T

array([[30.  , 40.  , 50.  , 60.  , 25.  ],
       [ 7.  , 10.  , 20.  , 12.  , 10.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  1.  ],
       [ 1.5 ,  1.6 ,  1.7 ,  1.8 ,  1.65]])

In [8]:
X.T.dot(X)

array([[9.22500e+03, 2.58000e+03, 1.05000e+02, 3.43250e+02],
       [2.58000e+03, 7.93000e+02, 3.70000e+01, 9.86000e+01],
       [1.05000e+02, 3.70000e+01, 3.00000e+00, 4.85000e+00],
       [3.43250e+02, 9.86000e+01, 4.85000e+00, 1.36625e+01]])

In [9]:
((X.T.dot(X)).dot(X.T)).dot(y)

array([2.09087927e+08, 5.88849833e+07, 2.42417142e+06, 7.79546458e+06])

In [10]:
alfa, betas = fit(X, y)

In [11]:
alfa, betas

(-916.818181818112,
 array([  2.21590909,  -5.45454545,  24.09090909, 582.95454545]))

In [12]:
def predict(X):
    Xb = np.c_[ np.ones(X.shape[0]), X]

    return Xb.dot( np.r_[alfa, betas] )

In [13]:
print(y)
predict(X)

[ 10  50 100 200  70]


array([ 10.,  50., 100., 200.,  70.])

In [14]:
prever = np.array([[40,  7, 1, 1.50]])
predict(prever)

array([32.15909091])